version: '3.7'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: redis:7.0-alpine
    volumes:
      - 'redis:/data'
  web:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - '${DOCKER_HOST_WEB_PORT:-3000}:3000'
    volumes:
      - 'bundle_cache:/bundle'
      - '.:/app'
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DISABLE_SPRING: 1
  worker:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - 'bundle_cache:/bundle'
      - '.:/app'
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DISABLE_SPRING: 1

volumes:
  redis:
  postgres:
  bundle_cache:
