version: '3.7'
services:
  redis:
    image: redis:7.0-alpine
    volumes:
      - 'redis:/data'
  web:
    depends_on:
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - '${DOCKER_HOST_WEB_PORT:-3000}:3000'
    volumes:
      - 'bundle_cache:/bundle'
      - '.:/app'
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DISABLE_SPRING: 1
  worker:
    depends_on:
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - 'bundle_cache:/bundle'
      - '.:/app'
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DISABLE_SPRING: 1

volumes:
  redis:
  bundle_cache:
